### PR TITLE
Add debug mode

### PR DESCRIPTION
**Pull request by BRIMIL01**
Allow for easier debugging of issues with the JS driver.

### CODE REVIEW

**Comment by cyphactor** [comment]
@BRIMIL01 please add a line item under "Next Release" for this feature in the ChangeLog.markdown.

**Comment by BRIMIL01** [comment]
Added line item

**Comment by cyphactor** [comment]
I think this needs to be properly rebased on the latest master. I did it locally and it was pretty smooth with a little correction in `ChangeLog.markdown` file. Although, I am having some difficulties manually testing it in Capture as I am now all of the sudden getting a weird failure I have never seen before. When, I then try your version I get yet another weird error. Needs further digging to properly verify this.

**Comment by cyphactor** [comment]
@BRIMIL01 what version of `phantomjs` did you test this with?

**Pull request closed without merging**
